#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - master
    
# Including commits with particular message or from specific user
only_commits:
  message: /build/                # Start a new build if message contains 'build'
image: Visual Studio 2017

# Test against the latest version of this Node.js version
environment:
  nodejs_version: "6"

# scripts that run after cloning repositorys
install:
  # by default, all script lines are interpreted as batch
  - echo This is batch
  # to run script as a PowerShell command prepend it with ps:
  - ps: Install-Product node $env:nodejs_version
  # batch commands start from cmd:
  - cmd: cd rotaract3220
  - cmd: npm install
  - cmd: npm install -g cordova
  - cmd: cordova platform add windows
  - cmd: cordova build windows -- --appx=uap
build:
    project: C:\projects\rotaract3220app\rotaract3220\platforms\windows\CordovaApp.Windows10.jsproj
test: off
deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Windows Universal App'
  provider: GitHub
  auth_token:
    secure: c/lXAytCIOqiw0TYXn2QtcrMzjhSWbE0wO9M2CJiOy2v2QoS2aMWB4zTV2Ud6xbB # your encrypted token from GitHub
  artifact: 
    - path: "C:\projects\rotaract3220app\rotaract3220\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_AnyCPU_Debug_Test\CordovaApp.Windows10_1.0.0.0_AnyCPU_Debug.appx"
    #/.*\.appx/            # upload all NuGet packages to release assets
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
